# Generated by Django 5.0.7 on 2025-12-20 11:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudinaryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='UUID یکتا برای تصویر', unique=True)),
                ('cloudinary_public_id', models.CharField(db_index=True, help_text='Public ID در Cloudinary', max_length=255, unique=True)),
                ('cloudinary_url', models.URLField(help_text='URL کامل تصویر در Cloudinary', max_length=500)),
                ('secure_url', models.URLField(blank=True, help_text='URL امن تصویر در Cloudinary (HTTPS)', max_length=500)),
                ('format', models.CharField(blank=True, help_text='فرمت تصویر (jpg, png, etc.)', max_length=10)),
                ('width', models.PositiveIntegerField(blank=True, help_text='عرض تصویر', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='ارتفاع تصویر', null=True)),
                ('bytes_size', models.PositiveIntegerField(blank=True, help_text='حجم فایل به بایت', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cloudinary Image',
                'verbose_name_plural': 'Cloudinary Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='menuitemimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Menu item image (legacy)', null=True, upload_to='business_menu/items/'),
        ),
        migrations.AddIndex(
            model_name='cloudinaryimage',
            index=models.Index(fields=['uuid'], name='business_me_uuid_1716ab_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudinaryimage',
            index=models.Index(fields=['cloudinary_public_id'], name='business_me_cloudin_823434_idx'),
        ),
        migrations.AddField(
            model_name='menuitemimage',
            name='cloudinary_image',
            field=models.ForeignKey(blank=True, help_text='تصویر در Cloudinary با UUID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_images', to='business_menu.cloudinaryimage'),
        ),
    ]
