# Generated by Django 5.0.7 on 2025-12-23 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_menu', '0003_category_menuset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Menu item category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='business_menu.category'),
        ),
    ]
