# Generated by Django 5.0.7 on 2025-12-28 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_menu', '0004_rename_business_me_restaur_idx_business_me_restaur_07242c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Package name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Package description')),
                ('package_price', models.DecimalField(decimal_places=2, help_text='Package price (discounted price)', max_digits=10)),
                ('image', models.ImageField(blank=True, help_text='Package image', null=True, upload_to='packages/')),
                ('is_active', models.BooleanField(default=True, help_text='Is this package active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of this item in package')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Package Item',
                'verbose_name_plural': 'Package Items',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='restaurant',
            field=models.ForeignKey(help_text='Related restaurant', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='business_menu.restaurant'),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='menu_item',
            field=models.ForeignKey(help_text='Menu item in package', on_delete=django.db.models.deletion.CASCADE, related_name='package_items', to='business_menu.menuitem'),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='package',
            field=models.ForeignKey(help_text='Related package', on_delete=django.db.models.deletion.CASCADE, related_name='package_items', to='business_menu.package'),
        ),
        migrations.AlterUniqueTogether(
            name='packageitem',
            unique_together={('package', 'menu_item')},
        ),
    ]
