# Generated by Django 5.0.7 on 2025-12-28 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_menu', '0005_package_packageitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('preview_static_path', models.CharField(blank=True, help_text='Static path for theme preview image (e.g. business_menu/themes/previews/classic.svg)', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Menu Theme',
                'verbose_name_plural': 'Menu Themes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_prices', models.BooleanField(default=True)),
                ('show_images', models.BooleanField(default=True)),
                ('show_descriptions', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_settings', to='business_menu.menutheme')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='business_menu.restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Settings',
                'verbose_name_plural': 'Restaurant Settings',
            },
        ),
    ]
