# Generated by GPT on 2025-12-28

from django.db import migrations


def seed_menu_themes(apps, schema_editor):
    MenuTheme = apps.get_model("business_menu", "MenuTheme")

    themes = [
        {
            "name": "Classic",
            "slug": "classic",
            "preview_static_path": "business_menu/themes/previews/classic.svg",
        },
        {
            "name": "Minimal White",
            "slug": "minimal-white",
            "preview_static_path": "business_menu/themes/previews/minimal-white.svg",
        },
        {
            "name": "Modern Midnight",
            "slug": "modern-midnight",
            "preview_static_path": "business_menu/themes/previews/modern-midnight.svg",
        },
        {
            "name": "Warm Sunset",
            "slug": "warm-sunset",
            "preview_static_path": "business_menu/themes/previews/warm-sunset.svg",
        },
    ]

    for t in themes:
        MenuTheme.objects.update_or_create(
            slug=t["slug"],
            defaults={
                "name": t["name"],
                "preview_static_path": t["preview_static_path"],
                "is_active": True,
            },
        )


def unseed_menu_themes(apps, schema_editor):
    MenuTheme = apps.get_model("business_menu", "MenuTheme")
    MenuTheme.objects.filter(slug__in=["classic", "minimal-white", "modern-midnight", "warm-sunset"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("business_menu", "0006_menutheme_restaurantsettings"),
    ]

    operations = [
        migrations.RunPython(seed_menu_themes, reverse_code=unseed_menu_themes),
    ]

