# Generated by Django 5.0.7 on 2026-01-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_menu', '0010_businessadmin_auth_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessadmin',
            options={'ordering': ['-created_at'], 'verbose_name': 'Business Menu Admin', 'verbose_name_plural': 'Business Menu Admins'},
        ),
        migrations.AddField(
            model_name='businessadmin',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', help_text='Payment status - users cannot login until payment is confirmed', max_length=20),
        ),
    ]
