# Generated by Django 5.1.2 on 2026-01-15 11:00

import django.db.models.deletion
from django.db import migrations, models


def keep_one_restaurant_per_admin(apps, schema_editor):
    """
    Data migration: Keep only one restaurant per admin before changing to OneToOneField.
    If an admin has multiple restaurants, keep the first active one, or the first one created.
    """
    Restaurant = apps.get_model('business_menu', 'Restaurant')
    BusinessAdmin = apps.get_model('business_menu', 'BusinessAdmin')
    
    # Group restaurants by admin
    for admin in BusinessAdmin.objects.all():
        restaurants = Restaurant.objects.filter(admin=admin).order_by('is_active', '-created_at')
        
        if restaurants.count() > 1:
            # Keep the first one (prefer active, then newest)
            keep_restaurant = restaurants.first()
            # Delete the rest
            restaurants.exclude(pk=keep_restaurant.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('business_menu', '0011_alter_businessadmin_options_and_more'),
    ]

    operations = [
        # First, ensure only one restaurant per admin
        migrations.RunPython(keep_one_restaurant_per_admin, migrations.RunPython.noop),
        # Then change the field to OneToOneField
        migrations.AlterField(
            model_name='restaurant',
            name='admin',
            field=models.OneToOneField(help_text='Admin of this restaurant (one admin = one restaurant)', on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='business_menu.businessadmin'),
        ),
    ]
