# Generated by Django 6.0.1 on 2026-03-06 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_menu', '0012_change_restaurant_admin_to_onetoone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=32)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(help_text='رستوران مرتبط', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='business_menu.restaurant')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شده'), ('preparing', 'در حال آماده\u200cسازی'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده'), ('refunded', 'مسترد شده')], db_index=True, default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='مبلغ کل', max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('stripe_order_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('items_json', models.JSONField(blank=True, default=dict, help_text='آیتم\u200cهای سفارش (JSON)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, help_text='مشتری (اختیاری)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='business_menu.customer')),
                ('restaurant', models.ForeignKey(help_text='رستوران', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='business_menu.restaurant')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('stripe_charge_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('succeeded', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده'), ('refunded', 'مسترد شده')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, help_text='سفارش مرتبط (اختیاری)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='business_menu.order')),
                ('restaurant', models.ForeignKey(help_text='رستوران', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='business_menu.restaurant')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
