# Generated by Django 6.0.1 on 2026-03-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_menu', '0013_add_customer_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقد'), ('online', 'آنلاین (کارت/استریپ)')], db_index=True, default='cash', help_text='نقد یا آنلاین', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('dine_in', 'در رستوران'), ('pickup', 'پیک\u200cآپ'), ('delivery', 'سفارش آنلاین با دلیوری')], db_index=True, default='dine_in', help_text='نوع سفارش: در رستوران، پیک\u200cآپ، یا دلیوری', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, help_text='کلید سشن مرورگر برای لیست سفارشات همین کاربر', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.CharField(blank=True, help_text='شماره میز (فقط برای Dine In)', max_length=32),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='allow_payment_cash',
            field=models.BooleanField(default=True, help_text='پرداخت نقدی مجاز'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='allow_payment_online',
            field=models.BooleanField(default=True, help_text='پرداخت آنلاین (کارت/استریپ) مجاز'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='has_delivery',
            field=models.BooleanField(default=False, help_text='آیا سفارش آنلاین با دلیوری فعال است؟ تا ادمین از اپ فعال نکرده باشد به کاربر نمایش داده نمی\u200cشود.'),
        ),
    ]
