# Generated by Django 6.0.1 on 2026-03-09 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_menu', '0014_order_service_and_restaurant_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='opening_hours',
            field=models.TextField(blank=True, help_text='Display text e.g. Mon–Fri 9:00–22:00'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='opening_hours_json',
            field=models.JSONField(blank=True, default=list, help_text='List of {day, open, close} for order validation; empty = no restriction'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField(help_text='Requested reservation date')),
                ('requested_time', models.CharField(blank=True, help_text='e.g. 19:00 or 7 PM', max_length=10)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=32)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='business_menu.restaurant')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['requested_date', 'requested_time'],
            },
        ),
    ]
