# Generated by Django 6.0.1 on 2026-03-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_menu', '0015_add_opening_hours_and_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the order is scheduled for (future date/time); null = order now.', null=True),
        ),
    ]
