# Generated by Django 6.0.1 on 2026-03-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_menu', '0016_add_order_scheduled_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessadmin',
            name='stripe_account_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Connect account ID (for receiving customer payments)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessadmin',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Customer ID for platform subscription payments', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessadmin',
            name='subscription_ends_at',
            field=models.DateTimeField(blank=True, help_text='End of current paid subscription period', null=True),
        ),
        migrations.AddField(
            model_name='businessadmin',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='End of 12-day free trial (set on signup)', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='country',
            field=models.CharField(blank=True, help_text='Country', max_length=100),
        ),
        migrations.AlterField(
            model_name='businessadmin',
            name='payment_status',
            field=models.CharField(choices=[('trial', 'Trial'), ('unpaid', 'Unpaid'), ('paid', 'Paid')], default='trial', help_text='trial=12-day free; unpaid=trial ended, subscribe to continue; paid=subscribed', max_length=20),
        ),
    ]
