# Generated by Django 6.0.1 on 2026-03-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_menu', '0017_add_trial_stripe_connect_restaurant_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupByIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, help_text='Client IP at signup', max_length=45, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Signup by IP',
                'verbose_name_plural': 'Signups by IP',
                'ordering': ['-created_at'],
            },
        ),
    ]
