# Generated by Django 6.0.1 on 2026-03-18 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_menu', '0019_add_pending_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guests_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of people'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Linked order when reservation was submitted with menu items (from cart).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='business_menu.order'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='order_details_json',
            field=models.JSONField(blank=True, default=list, help_text='Cart items (name, price, quantity) when reservation includes food order.'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default='cash', help_text='Cash or online; if online and cancelled, refund is issued.', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, help_text='Set when customer pays online; used for refund on cancel.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='max_guests_per_reservation',
            field=models.PositiveIntegerField(default=10, help_text='Max guests allowed per single reservation.'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='reservation_enabled',
            field=models.BooleanField(default=False, help_text='If True, reservation tab and reservation page are shown to customers.'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='total_tables',
            field=models.PositiveIntegerField(default=10, help_text='Max number of reservations per day (when full, no more slots for that day).'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='requested_time',
            field=models.CharField(blank=True, help_text='e.g. 19:00 or 19:30', max_length=10),
        ),
    ]
