# Generated by Django 6.0.1 on 2026-03-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_menu', '0020_reservation_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='closed_today',
            field=models.BooleanField(default=False, help_text='Manually marked closed for today'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cover_image_index',
            field=models.PositiveIntegerField(default=0, help_text='Index into gallery for cover/banner'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(blank=True, help_text='Public contact email for this restaurant', max_length=254),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='gallery',
            field=models.JSONField(blank=True, default=list, help_text='List of absolute image URLs for gallery'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.CharField(blank=True, help_text='Latitude as string (e.g. maps)', max_length=32),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo image file', null=True, upload_to='restaurants/logos/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.CharField(blank=True, help_text='Longitude as string (e.g. maps)', max_length=32),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal / ZIP code', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(blank=True, default='restaurant', help_text='Venue type label for the app (e.g. restaurant, cafe)', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.URLField(blank=True, help_text='Website URL', max_length=500),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp number', max_length=32),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='working_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Per-day hours, e.g. {"monday": {"enabled": true, "open": "09:00", "close": "22:00"}, ...}'),
        ),
    ]
