# Generated by Django 6.0.1 on 2026-03-22 11:01

from decimal import Decimal, InvalidOperation

from django.db import migrations, models


def _parse_coord(value):
    if value is None or value == "":
        return None
    s = str(value).strip().replace(",", ".")
    if not s:
        return None
    try:
        return Decimal(s)
    except (InvalidOperation, ValueError):
        return None


def copy_latlng_to_new_fields(apps, schema_editor):
    Restaurant = apps.get_model("business_menu", "Restaurant")
    for r in Restaurant.objects.all():
        la = _parse_coord(getattr(r, "latitude", None))
        lo = _parse_coord(getattr(r, "longitude", None))
        if la is not None and (la < -90 or la > 90):
            la = None
        if lo is not None and (lo < -180 or lo > 180):
            lo = None
        Restaurant.objects.filter(pk=r.pk).update(latitude_new=la, longitude_new=lo)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("business_menu", "0021_restaurant_profile_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="google_place_id",
            field=models.CharField(
                blank=True,
                help_text="Google Places place_id when chosen from autocomplete",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="latitude_new",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="WGS84 latitude (-90..90)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="longitude_new",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="WGS84 longitude (-180..180)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.RunPython(copy_latlng_to_new_fields, noop_reverse),
        migrations.RemoveField(model_name="restaurant", name="latitude"),
        migrations.RemoveField(model_name="restaurant", name="longitude"),
        migrations.RenameField(model_name="restaurant", old_name="latitude_new", new_name="latitude"),
        migrations.RenameField(model_name="restaurant", old_name="longitude_new", new_name="longitude"),
    ]
