# Generated by Django 6.0.1 on 2026-03-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_menu', '0022_restaurant_latlng_decimal_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='public_slug',
            field=models.SlugField(blank=True, help_text='Optional public URL segment for /m/<slug>/ (e.g. my-bistro)', max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='WGS84 latitude [-90, 90]', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='WGS84 longitude [-180, 180]', max_digits=9, null=True),
        ),
    ]
