# Generated by Django 6.0.1 on 2026-03-26 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_menu', '0024_online_ordering_settings_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('closed_today', models.BooleanField(default=False)),
                ('max_guests_per_reservation', models.PositiveIntegerField(default=8)),
                ('advance_booking_days', models.PositiveIntegerField(default=14)),
                ('schedule', models.JSONField(blank=True, default=dict)),
                ('reservation_duration', models.PositiveIntegerField(default=60)),
                ('buffer_minutes', models.PositiveIntegerField(default=15)),
                ('blocked_dates', models.JSONField(blank=True, default=list)),
                ('tables', models.JSONField(blank=True, default=list)),
                ('floor_plan_image', models.ImageField(blank=True, null=True, upload_to='restaurants/floorplans/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_settings', to='business_menu.restaurant')),
            ],
            options={
                'verbose_name': 'Reservation Settings',
                'verbose_name_plural': 'Reservation Settings',
            },
        ),
    ]
