# Generated by Django 5.1.15 on 2026-07-06 19:07

import django.db.models.deletion
from django.db import migrations, models


def populate_customer_business_admin(apps, schema_editor):
    Customer = apps.get_model('business_menu', 'Customer')
    Restaurant = apps.get_model('business_menu', 'Restaurant')
    restaurant_admins = dict(Restaurant.objects.values_list('id', 'admin_id'))
    for customer in Customer.objects.filter(business_admin__isnull=True).only('id', 'restaurant_id'):
        admin_id = restaurant_admins.get(customer.restaurant_id)
        if admin_id:
            Customer.objects.filter(pk=customer.pk).update(business_admin_id=admin_id)


class Migration(migrations.Migration):

    dependencies = [
        ('business_menu', '0025_reservationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='business_admin',
            field=models.ForeignKey(blank=True, help_text='Business owner/admin for this customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='business_menu.businessadmin'),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='business_menu.order'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_order_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='orders_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.CharField(db_index=True, default='online_order', max_length=32),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(populate_customer_business_admin, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['restaurant', 'phone'], name='business_me_restaur_53c3e3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['business_admin', 'phone'], name='business_me_busines_010cbe_idx'),
        ),
    ]
