# Generated by Django 5.1.2 on 2026-10-01 16:13

import business_menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_menu', '0032_businessadmin_subscription_store_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='occupies_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timezone-aware end of reservation duration plus buffer.', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_setup_failed',
            field=models.BooleanField(default=False, help_text='True only when initial Stripe setup failed and this request may be retried safely.'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='request_id',
            field=models.UUIDField(blank=True, editable=False, help_text='Optional client idempotency key for safe reservation retries.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='requested_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timezone-aware start instant; date/time fields remain for API compatibility.', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='timezone',
            field=models.CharField(blank=True, help_text='IANA timezone used only for reservations, for example Europe/Berlin.', max_length=64, validators=[business_menu.models.validate_iana_timezone]),
        ),
    ]
