# Generated by Django 5.1.2 on 2026-10-02 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_menu', '0035_businessadmin_subscription_account_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessadmin',
            name='subscription_access_block_reason',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='businessadmin',
            name='subscription_access_blocked',
            field=models.BooleanField(default=False, help_text='Explicit service-access block set by a superuser; provider records remain unchanged.'),
        ),
        migrations.AddField(
            model_name='businessadmin',
            name='subscription_access_blocked_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='businessadmin',
            name='subscription_access_blocked_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessadmin',
            name='subscription_last_admin_action_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
