# Generated by Django 5.0.7 on 2026-01-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_phone_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('superuser', 'Super User'), ('admin', 'Admin'), ('operator', 'Operator'), ('business_owner', 'Business Owner'), ('customer', 'Customer')], default='customer', max_length=32),
        ),
    ]
